import { ItemType, ProjectType } from "@/types/types";
import { Database } from "./database.types";


// Supabase row (autogenerated type)
export type DbItemType = Database["public"]["Tables"]["items"]["Row"];
export type DbInsertItemType = Database["public"]["Tables"]["items"]["Insert"];
export type DbUpdateItemType = Database["public"]["Tables"]["items"]["Update"];

export type DbProjectType = {
  uuid: string;
  title: string;
  user_id: string | null;
  parent: string | null;
  ordering: number | null;
  pinned: boolean;
  meta: ProjectType["meta"];
  iv: string | null;
  is_encrypted: boolean;
  ciphertext: string | null;
  key_version: number;
  created_at: string;
  modified_at: string;
  deleted_at: string | null;
  version: number;
  synced_at: string;
  modified_by: string;
};

export type DbInsertProjectType = {
  uuid: string;
  title: string;
  user_id?: string | null;
  parent?: string | null;
  ordering?: number | null;
  pinned?: boolean;
  meta?: ProjectType["meta"];
  iv?: string | null;
  is_encrypted?: boolean;
  ciphertext?: string | null;
  key_version?: number;
  created_at?: string;
  modified_at?: string;
  deleted_at?: string | null;
  version?: number;
  synced_at?: string;
  modified_by: string;
};

// Mapper functions
export function mapDbToItem(row: DbItemType): ItemType {
  return {
    id: row.id, // not to use!
    uuid: row.uuid,
    userId: row.user_id,
    title: row.title,
    type: row.type,
    status: row.status,
    category: row.category,
    projectId: row.project_id,
    calendar: row.calendar,
    scheduledAt: row.scheduled_at,
    completedAt: row.completed_at,
    tzOffset: row.tz_offset,
    tzIANA: row.tz_iana,
    dueType: row.due_type,
    duration: row.duration,
    parent: row.parent,
    ordering: (row.ordering as ItemType["ordering"]) ?? null,
    notification: row.notification,
    pinned: row.pinned,
    meta: row.meta,
    recurrence: row.recurrence,
    iv: row.iv,
    isEncrypted: row.is_encrypted,
    ciphertext: row.ciphertext,
    keyVersion: row.key_version,
    createdAt: row.created_at,
    modifiedAt: row.modified_at,
    deletedAt: row.deleted_at,
    version: row.version,
    syncedAt: row.synced_at,
    modifiedBy: row.modified_by,
  };
}

export function mapItemToDbInsert(item: ItemType): DbInsertItemType {
  return {
    // id: don't have!
    uuid: item.uuid,
    user_id: item.userId,
    title: item.title,
    type: item.type,
    status: item.status,
    category: item.category,
    project_id: item.projectId,
    calendar: item.calendar,
    scheduled_at: item.scheduledAt,
    completed_at: item.completedAt,
    tz_offset: item.tzOffset,
    tz_iana: item.tzIANA,
    due_type: item.dueType,
    duration: item.duration,
    parent: item.parent,
    ordering: item.ordering,
    notification: item.notification,
    pinned: item.pinned,
    meta: item.meta,
    recurrence: item.recurrence,
    iv: item.iv,
    is_encrypted: item.isEncrypted,
    ciphertext: item.ciphertext,
    key_version: item.keyVersion,
    created_at: item.createdAt,
    modified_at: item.modifiedAt,
    deleted_at: item.deletedAt,
    version: item.version,
    synced_at: item.syncedAt || undefined,
    modified_by: item.modifiedBy,
  };
}

export function mapItemToDbUpdate(item: ItemType): DbUpdateItemType {
  return {
    // id: item.id,
    uuid: item.uuid,
    user_id: item.userId,
    title: item.title,
    type: item.type,
    status: item.status,
    category: item.category,
    project_id: item.projectId,
    calendar: item.calendar,
    scheduled_at: item.scheduledAt,
    completed_at: item.completedAt,
    tz_offset: item.tzOffset,
    tz_iana: item.tzIANA,
    due_type: item.dueType,
    duration: item.duration,
    parent: item.parent,
    ordering: item.ordering,
    notification: item.notification,
    pinned: item.pinned,
    meta: item.meta,
    recurrence: item.recurrence,
    iv: item.iv,
    is_encrypted: item.isEncrypted,
    ciphertext: item.ciphertext,
    key_version: item.keyVersion,
    created_at: item.createdAt,
    modified_at: item.modifiedAt,
    deleted_at: item.deletedAt,
    version: item.version,
    synced_at: item.syncedAt || undefined,
    modified_by: item.modifiedBy,
  };
}

export function mapDbToProject(row: DbProjectType): ProjectType {
  return {
    uuid: row.uuid,
    title: row.title,
    userId: row.user_id,
    parent: row.parent,
    ordering: row.ordering,
    pinned: row.pinned,
    meta: row.meta,
    iv: row.iv,
    isEncrypted: row.is_encrypted,
    ciphertext: row.ciphertext,
    keyVersion: row.key_version,
    createdAt: row.created_at,
    modifiedAt: row.modified_at,
    deletedAt: row.deleted_at,
    version: row.version,
    syncedAt: row.synced_at,
    modifiedBy: row.modified_by,
  };
}

export function mapProjectToDbInsert(project: ProjectType): DbInsertProjectType {
  return {
    uuid: project.uuid,
    title: project.title,
    user_id: project.userId,
    parent: project.parent,
    ordering: project.ordering,
    pinned: project.pinned,
    meta: project.meta,
    iv: project.iv,
    is_encrypted: project.isEncrypted,
    ciphertext: project.ciphertext,
    key_version: project.keyVersion,
    created_at: project.createdAt,
    modified_at: project.modifiedAt,
    deleted_at: project.deletedAt,
    version: project.version,
    synced_at: project.syncedAt || undefined,
    modified_by: project.modifiedBy,
  };
}
